### ISSUE TITLE
Code issues with AITKKeras notebook

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#10]
Added:
```python
%pip install aitk --quiet
```
Changed code block three from:
```python
(x_train, y_train), (x_test, y_test) = await mnist.load_data_async()
```
To:
```python
(x_train, y_train), (x_test, y_test) =  mnist.load_data()
```

For additional comments see  [Google Colab AITKKeras](https://colab.research.google.com/drive/1bu0RwJJgfNPNi4z-B1m690-uD3tdJ8iU?usp=drive_link#scrollTo=gjsgVaFKzJMU)

**Comment by lmeeden1** [comment]
Removed notebook
