### ISSUE TITLE
Adding install for CartWorld Notebook

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#12]
Install must be added for CartWorld notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab CartWorld Notebook](https://colab.research.google.com/drive/1OJRFSo67AMBMXlvdhiivkYoJTFlKAit9?usp=drive_link#scrollTo=TGwHk62H4Ks_).

**Comment by lmeeden1** [comment]
fixed
