### ISSUE TITLE
Adding install for CollectReinforcementData

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#14]
Install must be added for CollectReinforcementData notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab CollectReinforcementData Notebook](https://colab.research.google.com/drive/1514HHbryE1OVmDczl4IuukhbTzLI7V-l?usp=drive_link).

**Comment by lmeeden1** [comment]
fixed
