### ISSUE TITLE
Adding install for CompassAndBeacon

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#15]
Install must be added for CompassAndBeacon notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab CompassAndBeacon Notebook](https://colab.research.google.com/drive/1rVHpN1V6zU6XSCOEZMu6NTDwR31_wqOw?usp=drive_link.

**Comment by lmeeden1** [comment]
fixed
