### ISSUE TITLE
Issue with world in SeekLight notebook

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#19]
The world "LightEnclosed" is not recognized in line 4 of the SeekLight notebook.

```python
world = aitk.robots.load_world("LightEnclosed")
```

Fore more comments see: [Google Colab SeekLight notebook](https://colab.research.google.com/drive/1916WH2_07u7TmutGUxMewkxgni5tG2P3?usp=sharing#scrollTo=0OHMFQU4cBbB)

**Comment by lmeeden1** [comment]
fixed
