### ISSUE TITLE
Adding install for StringGA

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#20]
Install must be added for StringGA notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab StringGA Notebook](https://colab.research.google.com/drive/1IJSmwut1s6zv6aLV7n-QEw5vNuuXh3Mu?usp=sharing#scrollTo=ROMhlHQgd2yI).

**Comment by lmeeden1** [comment]
fixed
