### ISSUE TITLE
Issues with Subsumption notebook

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#22]
The install must be added:

```python
%pip install aitk --quiet
```

In addition to the problem with the install, the LightEnclosed world is once again not able to load, so the rest of the notebook breaks. This occurs in line 9.

```python
world = aitk.robots.load_world("LightEnclosed")
```

For more comments see: [Google Colab Subsumption notebook](https://colab.research.google.com/drive/10zd3Db2c4rZ3tRuy5OEnuoS5G5UKh1VQ?usp=sharing#scrollTo=MbfSCq5ce301).

**Comment by lmeeden1** [comment]
fixed
