### ISSUE TITLE
 Adding install for TrainFollow 

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#23]
Install must be added for TrainFollow notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab TrainFollow Notebook](https://colab.research.google.com/drive/1vo14EDmIa6C-fEgoXYakGJHppOzkzHA4?usp=sharing).

**Comment by lmeeden1** [comment]
fixed
