### ISSUE TITLE
Adding install for ZigZagWall

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#25]
Install must be added for ZigZagWall notebook in order to run on Google Colab.

```python
%pip install aitk --quiet
```

For more comments see [Google Colab ZigZagWall Notebook](https://colab.research.google.com/drive/1G06mHulyTwSK8SfHInItzQOCjG-O7fVl?usp=sharing).

**Comment by lmeeden1** [comment]
this notebook has been removed
