### ISSUE TITLE
Issues with ClassifyDigitsWithPCA notebook

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#27]
Once again having an issues with the input dataset as in the ClassifyingDigits notebook.

In line 3:
Code:
```python
inputs = get_digit_inputs()
```
Throws this error:
```python
FileNotFoundError                         Traceback (most recent call last)

<ipython-input-3-73e7cc90aa80> in <cell line: 1>()
----> 1 inputs = get_digit_inputs()
      2 inputs.shape

<ipython-input-2-cdd8a157308e> in get_digit_inputs()
      1 def get_digit_inputs():
      2     """Each digit is represented by a 6x6 grid of 1's and 0's separated by blank lines."""
----> 3     fp = open("digits.data", "r")
      4     data = []
      5     while True:

FileNotFoundError: [Errno 2] No such file or directory: 'digits.data'
```

This then breaks the code further down when trying to access the input dataset. Further, an install statement must be added before neural networks are used.

For more comments regarding this notebook see: [Google Colab ClassifyDigitsWithPCA notebook](https://colab.research.google.com/drive/1iNkn6cugPVRerrP4OS468zB1yzjxz_zr?usp=drive_link#scrollTo=6N2DKs8K534O)

**Comment by lmeeden1** [comment]
Fixed
