### ISSUE TITLE
Issue with build_network function

### ISSUE THREAD

**Issue by morganmcerlean** [ArtificialIntelligenceToolkit/aitk#68]
<img width="1080" alt="Screen Shot 2024-08-03 at 9 41 34 PM" src="https://github.com/user-attachments/assets/3202c127-6ff3-4fc3-a446-46674e405eea">
Error is attached.

**Comment by dsblank** [comment]
What would make any issue report better is to include the simplest code possible that will recreate the problem. If you include it as text, then someone can copy/paste into python to quickly try to recreate the issue. Such as:

## How to Recreate Issue

1. Create a notebook on colab
2. Install aitk: `%pip install aitk`
3. Run the following code:

```
from aitk.networks import SimpleNetwork
SimpleNetwork(10, 5, 10)
```
This will raise the following exception:
```
(paste entire stack trace here)
```

**Comment by dsblank** [comment]
I've created aitk version 2.1.0 that requires a specific version of numpy and tensorflow.

In my testing, it works on colab with CPU and T4 GPU.

The only downside that I see so far is that the `%pip install aitk` will take quite a bit longer (on colab) because it has to install a different version of tensorflow.

Please check it out and let us know if it works!

**Comment by morganmcerlean** [comment]
Doug, it is working now! Thank you so much. There is this one error that is printing when installing, but it doesn't seem to be affecting the build network function or any other code cells. 

Issue:
1. Open a notebooks in colab
2. Results in the following code error when running %pip install aitk:
<img width="1193" alt="Screen Shot 2024-08-04 at 12 38 38 PM" src="https://github.com/user-attachments/assets/2f19628b-7a11-4470-9d4e-6f7882c4d883">

**Comment by dsblank** [comment]
I saw that too, but I don't think the package `tf-keras` is needed by us, but there could still be other issues. Probably a good idea to re-check all `aitk.network` notebooks.

**Comment by dsblank** [comment]
Closing this issue as it appears fixed. Please reopen if you find something related that fails. Thanks for the report!
